name = "dsgames-catalog"
main = "src/index.js"
compatibility_date = "2026-09-07"

[vars]
APP_NAME = "DSGames"

[[d1_databases]]
binding = "DB"
database_name = "dsgames"
database_id = "64370aae-5251-4698-87b8-d29182a178a4"
